Process configchange event and save the parameters in some data structure.
eosnetworkfoundation/eos-evm-node pull request #190
Opened 2024-02-09 01:35 UTC by yarkinwho

Resolve #186 

The planned implementation is like this:

1 ship_receiver_plugin will check if it received a configchange event, if found, make sure it's the first related action in a block, save the new config in the resulting native_block/

2 block_conversion_plugin will make sure if there's a new config in the incoming native_block, it should be the first one native block for a resulting evm block. Then: 
a save the new config in the resulting evm block
b change the evm block's consensus_parameter_index to it's own height.

3 blockchain_plugin will detect if there's new config coming in with the evm blocks. if so:
a save new parameters
b verify_chain for the blocks before if necessary

c insert the incoming blcok
d verify chain (may be not necessary)

-- EDIT: after some double thinking, we do not need this for blockchain_plugin, let's just try a normal process first.

2024-03-01 06:06 UTC, yarkinwho commented on src/block_conversion_plugin.hpp
> +struct gas_parameter_data_v1 {
Yeah, was copied from there back then. Didn't notice it was changed.

2024-03-01 06:49 UTC, yarkinwho commented on src/channels.hpp
> +   struct consensus_parameter_event {
forgot to delete. deleted

2024-03-01 06:49 UTC, yarkinwho commented on src/block_conversion_plugin.hpp
> +struct gas_parameter_data_v1 {
fixed

2024-03-05 00:54 UTC, elmato commented on src/block_conversion_plugin.cpp
> +                  curr.consensus_parameter_index = curr.header.number;
We should save here the consensus parameters to db

2024-03-05 00:54 UTC, elmato commented on src/blockchain_plugin.cpp
> +
We don't need this and the last_consensus_parameters_index / last_consensus_parameters variables

2024-03-05 00:54 UTC, elmato commented on src/blockchain_plugin.cpp
> +      std::optional<eosevm::ConsensusParameters>              last_consensus_parameters;
This is not needed

2024-03-14 23:43 UTC, elmato requested changes
~~As a last request, i think we should remove the consensus parameters previously added [here](https://github.com/eosnetworkfoundation/eos-evm-node/pull/190/files#diff-80593411e546176bee31482490117bdb26476e73e12a7b567722ec2b3597aa08R275), when we are reverting each of the forked native blocks [here](https://github.com/eosnetworkfoundation/eos-evm-node/blob/e87222ac61315189300f8751a43ecb3b9fda1e5c/src/block_conversion_plugin.cpp#L237
)~~

We decided to store the hash of the ConsensusParameters values, so there is no need to remove it when a fork happens on the native side

2024-03-16 14:47 UTC, elmato approved these changes

2024-03-20 02:17 UTC, merged